Rails/pinterwest/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
  	member do
  	  put "like", to: "pins#upvote"
  	end
  end

  root "pins#index"  
end

Rails/pinterwest/app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

Rails/pinterwest/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins

  def admin?
    admin
  end
end

Rails/pinterwest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

Rails/pinterwest/app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :authorized_user, only: [:edit, :update, :destroy]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show

	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Successfully created new Pin"
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was Successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end

	def authorized_user
		if current_user.admin == false
	  		@pin = current_user.pins.find_by(id: params[:id])
	  		redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
	  	end
	  	# if @pin == nil and current_user.admin == false
	  	# 	redirect_to pins_path, notice: "Not authorized to edit this pin"
	  	# end
	end


end

Rails/pinterwest/app/helpers/pins_helper.rb
module PinsHelper
end

Rails/pinterwest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterwhore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' />
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-brand">
				<%= link_to "Pinterwhore", root_path, method: :get %>
			</div>

			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "New Pin", new_pin_path %></li>
					<li><%= link_to "Account", edit_user_registration_path %></li>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<li><%= link_to "Sign In", new_user_session_path %></li>
				</ul>
			<% end %>
		</div>
	</nav>

	<div class="container">
		<% flash.each do |name,msg| %>
			<%= content_tag :div, msg, class: "alert alert-info" %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>